### ISSUE TITLE
the @codemirror/comment  has been merged into @codemirror/commands

### ISSUE THREAD

**Issue by xiaoyugg** [replit/codemirror-vscode-keymap#6]
the @codemirror/comment  has been merged into @codemirror/commands, so I can't install this package

**Comment by sergeichestakov** [comment]
Thanks for flagging! Fixed in [latest commit](https://github.com/replit/codemirror-vscode-keymap/commit/9ab6060f4b73f0b5006fcf72716489d78b31b65e) and published in `6.0.2`
